apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Keycloak server with HTTPS
    iconClass: icon-sso
    openshift.io/display-name: Keycloak
    tags: keycloak
    version: 4.0.0.Beta2
  name: keycloak-https
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's https port.
    labels:
      application: ${APPLICATION_NAME}
    name: secure-${APPLICATION_NAME}
  spec:
    ports:
    - port: 8443
      targetPort: 8443
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  id: ${APPLICATION_NAME}-https
  kind: Route
  metadata:
    annotations:
      description: Route for application's https service.
    labels:
      application: ${APPLICATION_NAME}
    name: secure-${APPLICATION_NAME}
  spec:
    host: ${HOSTNAME_HTTPS}
    tls:
      termination: passthrough
    to:
      name: secure-${APPLICATION_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: quay.io/duke253/keycloak-customized:1.0
          env:
          - name: KEYCLOAK_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: keycloak-secret
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: keycloak-secret
          - name: DB_VENDOR
            value: ${DB_VENDOR}
          - name: JGROUPS_DISCOVERY_PROTOCOL
            value: dns.DNS_PING
          - name: JGROUPS_DISCOVERY_PROPERTIES
            value: dns_query=${APPLICATION_NAME}.${NAMESPACE}.svc.cluster.local
          - name: DB_ADDR
            value: ${DB_ADDR}
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: keycloak-database
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: keycloak-database
          - name: DB_DATABASE
            value: ${DB_DATABASE}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /auth/realms/master
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 360
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /auth/realms/master
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 360
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /opt/jboss/keycloak/standalone/log
            name: kc-logs-1
        - image: quay.io/duke253/filebeat-customized:1.5
          imagePullPolicy: Always
          name: kc-filebeat-1
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
          - mountPath: /opt/jboss/keycloak/standalone/log
            name: kc-logs-1
            readOnly: true
        volumes:
        - name: kc-logs-1
          emptyDir: {}
    triggers:
    - type: ConfigChange
parameters:
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: keycloak
- description: DB vendor (H2, POSTGRES, MYSQL or MARIADB)
  displayName: DB Vendor
  name: DB_VENDOR
  required: true
  value: POSTGRES
- description: DB host address
  displayName: DB Host Address
  name: DB_ADDR
  required: true
  value: 178.154.233.162
- description: DB name
  displayName: DB Name
  name: DB_DATABASE
  required: true
  value: keycloakdb
- description: 'Custom hostname for http service route. Leave blank for default hostname, e.g.: <application-name>.<project>.<default-domain-suffix>'
  displayName: Custom http Route Hostname
  name: HOSTNAME_HTTP
- description: 'Custom hostname for https service route. Leave blank for default hostname, e.g.: <application-name>.<project>.<default-domain-suffix>'
  displayName: Custom https Route Hostname
  name: HOSTNAME_HTTPS
- description: This namespace is a part of DNS query sent to Kubernetes API. This query allows the DNS_PING protocol to extract cluster members. This parameter might be removed once https://issues.jboss.org/browse/JGRP-2292 is implemented.
  displayName: Namespace used for DNS discovery
  name: NAMESPACE
  required: true